apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test-api
  labels:
    app: springboot
spec:
  replicas: 1 
  selector:
    matchLabels: 
      app: springboot
  template:
    metadata:
      labels: 
        app: springboot
    spec:
      containers:
        - name: api-spring
          image: mbodji/api-spring-test:v2.0 
          env: 
            - name: MYSQL_HOST 
              valueFrom:
                configMapKeyRef:
                  name: api-configmap 
                  key: mysql_host
            - name: MYSQL_DATABASE 
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: mysql_database
            - name: MYSQL_USERNAME 
              valueFrom:
                secretKeyRef:
                  name: api-secret 
                  key: mysql_user
            - name: MYSQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: mysql_password
          ports:
            - containerPort: 8080
